# Split
SPLIT_KEYBOARD = yes

# Custom Keycodes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
# TAP_DANCE_ENABLE = yes

# Rotary Encoder
# ENCODER_ENABLE = yes

# OLED Screen
# OLED_ENABLE = yes
# OLED_DRIVER = SSD1306

# Per-key RGB Matrix
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = bitbang

# Trackball
# POINTING_DEVICE_ENABLE = yes
# POINTING_DEVICE_DRIVER = pmw3360
