# Split
SPLIT_KEYBOARD = yes

# Custom Keycodes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
# TAP_DANCE_ENABLE = yes

# Per-key RGB Matrix
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = bitbang